version: '3'
services:
  grafana:
    container_name: grafana
    image: shana0408/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/conf:/usr/share/grafana/conf
  prometheus:
    image: shana0408/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/config/targets.json:/etc/prometheus/targets.json
      - ./prometheus/config/prometheus_rules.yml:/etc/prometheus/prometheus_rules/yml
      - ./prometheus/data:/prometheus
    extra_hosts:
      - "yukari:192.168.1.138"
  node-exporter:
    image: shana0408/node-exporter
    container_name: node_exporter
    restart: unless-stopped
    ports:
     - 9100:9100
